title: "Tarush Shankar"
logo: "/tarush_headshot_new.jpeg"
description: "Research Assistant @ COMBiN Research Lab UofA | prev-Software Developer @ CityScan Technologies"
theme: jekyll-theme-minimal



